exclude: |
  (?x)^(
    \.venv/|
    artifacts/|
    dl/|
    node_modules/|
    repo_.*/|
    aws/dist/|
    attic/|
    tasks/
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff-format
