[tool.ruff]
line-length = 100
target-version = "py312"

extend-exclude = [
  ".venv",
  "artifacts",
  "dl",
  "node_modules",
  "repo_*",
  "aws/dist",
  "attic",
  "tasks",
]

[tool.ruff.lint]
select = ["E", "F", "B", "C90", "I"]

[tool.ruff.lint.per-file-ignores]
"ui/studio.py" = ["E501"]
"master_ai/runtime/agent.py" = ["C901"]
"master_ai/agents/planner.py" = ["C901", "B904"]
"master_ai/runtime/fixers.py" = ["E501"]
